Using Theano backend.
INFO:root:Acquiring data/wn18/wordnet-mlj12-train.txt ..
INFO:root:Acquiring data/wn18/wordnet-mlj12-valid.txt ..
INFO:root:Acquiring data/wn18/wordnet-mlj12-test.txt ..
INFO:root:Samples: 141442, no. batches: 10 -> batch size: 14145
INFO:root:Epoch no. 1 of 500 (samples: 141442)
INFO:root:Loss: 1.2912 +/- 0.0463
INFO:root:Epoch no. 2 of 500 (samples: 141442)
INFO:root:Loss: 1.0059 +/- 0.0257
INFO:root:Epoch no. 3 of 500 (samples: 141442)
INFO:root:Loss: 0.8135 +/- 0.0065
INFO:root:Epoch no. 4 of 500 (samples: 141442)
INFO:root:Loss: 0.7201 +/- 0.0144
INFO:root:Epoch no. 5 of 500 (samples: 141442)
INFO:root:Loss: 0.665 +/- 0.0147
INFO:root:Epoch no. 6 of 500 (samples: 141442)
INFO:root:Loss: 0.6281 +/- 0.0155
INFO:root:Epoch no. 7 of 500 (samples: 141442)
INFO:root:Loss: 0.6013 +/- 0.0147
INFO:root:Epoch no. 8 of 500 (samples: 141442)
INFO:root:Loss: 0.5812 +/- 0.0133
INFO:root:Epoch no. 9 of 500 (samples: 141442)
INFO:root:Loss: 0.566 +/- 0.014
INFO:root:Epoch no. 10 of 500 (samples: 141442)
INFO:root:Loss: 0.5541 +/- 0.014
INFO:root:Epoch no. 11 of 500 (samples: 141442)
INFO:root:Loss: 0.5444 +/- 0.0122
INFO:root:Epoch no. 12 of 500 (samples: 141442)
INFO:root:Loss: 0.5341 +/- 0.0127
INFO:root:Epoch no. 13 of 500 (samples: 141442)
INFO:root:Loss: 0.5273 +/- 0.0112
INFO:root:Epoch no. 14 of 500 (samples: 141442)
INFO:root:Loss: 0.5209 +/- 0.0112
INFO:root:Epoch no. 15 of 500 (samples: 141442)
INFO:root:Loss: 0.516 +/- 0.0113
INFO:root:Epoch no. 16 of 500 (samples: 141442)
INFO:root:Loss: 0.5095 +/- 0.0107
INFO:root:Epoch no. 17 of 500 (samples: 141442)
INFO:root:Loss: 0.5045 +/- 0.0101
INFO:root:Epoch no. 18 of 500 (samples: 141442)
INFO:root:Loss: 0.5004 +/- 0.0106
INFO:root:Epoch no. 19 of 500 (samples: 141442)
INFO:root:Loss: 0.4972 +/- 0.01
INFO:root:Epoch no. 20 of 500 (samples: 141442)
INFO:root:Loss: 0.4944 +/- 0.0099
INFO:root:Epoch no. 21 of 500 (samples: 141442)
INFO:root:Loss: 0.4902 +/- 0.0097
INFO:root:Epoch no. 22 of 500 (samples: 141442)
INFO:root:Loss: 0.4869 +/- 0.0104
INFO:root:Epoch no. 23 of 500 (samples: 141442)
INFO:root:Loss: 0.4836 +/- 0.0098
INFO:root:Epoch no. 24 of 500 (samples: 141442)
INFO:root:Loss: 0.4802 +/- 0.0096
INFO:root:Epoch no. 25 of 500 (samples: 141442)
INFO:root:Loss: 0.4779 +/- 0.0084
INFO:root:Epoch no. 26 of 500 (samples: 141442)
INFO:root:Loss: 0.4755 +/- 0.0086
INFO:root:Epoch no. 27 of 500 (samples: 141442)
INFO:root:Loss: 0.4742 +/- 0.0087
INFO:root:Epoch no. 28 of 500 (samples: 141442)
INFO:root:Loss: 0.4722 +/- 0.0095
INFO:root:Epoch no. 29 of 500 (samples: 141442)
INFO:root:Loss: 0.4696 +/- 0.0084
INFO:root:Epoch no. 30 of 500 (samples: 141442)
INFO:root:Loss: 0.4684 +/- 0.0085
INFO:root:Epoch no. 31 of 500 (samples: 141442)
INFO:root:Loss: 0.4658 +/- 0.0074
INFO:root:Epoch no. 32 of 500 (samples: 141442)
INFO:root:Loss: 0.4642 +/- 0.0079
INFO:root:Epoch no. 33 of 500 (samples: 141442)
INFO:root:Loss: 0.4634 +/- 0.0076
INFO:root:Epoch no. 34 of 500 (samples: 141442)
INFO:root:Loss: 0.4609 +/- 0.0079
INFO:root:Epoch no. 35 of 500 (samples: 141442)
INFO:root:Loss: 0.4598 +/- 0.0084
INFO:root:Epoch no. 36 of 500 (samples: 141442)
INFO:root:Loss: 0.4584 +/- 0.0074
INFO:root:Epoch no. 37 of 500 (samples: 141442)
INFO:root:Loss: 0.4563 +/- 0.008
INFO:root:Epoch no. 38 of 500 (samples: 141442)
INFO:root:Loss: 0.455 +/- 0.0081
INFO:root:Epoch no. 39 of 500 (samples: 141442)
INFO:root:Loss: 0.453 +/- 0.0079
INFO:root:Epoch no. 40 of 500 (samples: 141442)
INFO:root:Loss: 0.4519 +/- 0.0087
INFO:root:Epoch no. 41 of 500 (samples: 141442)
INFO:root:Loss: 0.4505 +/- 0.0069
INFO:root:Epoch no. 42 of 500 (samples: 141442)
INFO:root:Loss: 0.4497 +/- 0.0079
INFO:root:Epoch no. 43 of 500 (samples: 141442)
INFO:root:Loss: 0.449 +/- 0.0077
INFO:root:Epoch no. 44 of 500 (samples: 141442)
INFO:root:Loss: 0.448 +/- 0.0079
INFO:root:Epoch no. 45 of 500 (samples: 141442)
INFO:root:Loss: 0.4463 +/- 0.0078
INFO:root:Epoch no. 46 of 500 (samples: 141442)
INFO:root:Loss: 0.4447 +/- 0.0077
INFO:root:Epoch no. 47 of 500 (samples: 141442)
INFO:root:Loss: 0.4443 +/- 0.0079
INFO:root:Epoch no. 48 of 500 (samples: 141442)
INFO:root:Loss: 0.4426 +/- 0.0077
INFO:root:Epoch no. 49 of 500 (samples: 141442)
INFO:root:Loss: 0.442 +/- 0.0079
INFO:root:Epoch no. 50 of 500 (samples: 141442)
INFO:root:Loss: 0.4415 +/- 0.0076
INFO:root:Epoch no. 51 of 500 (samples: 141442)
INFO:root:Loss: 0.44 +/- 0.0076
INFO:root:Epoch no. 52 of 500 (samples: 141442)
INFO:root:Loss: 0.4395 +/- 0.0077
INFO:root:Epoch no. 53 of 500 (samples: 141442)
INFO:root:Loss: 0.4377 +/- 0.0078
INFO:root:Epoch no. 54 of 500 (samples: 141442)
INFO:root:Loss: 0.4375 +/- 0.0067
INFO:root:Epoch no. 55 of 500 (samples: 141442)
INFO:root:Loss: 0.437 +/- 0.007
INFO:root:Epoch no. 56 of 500 (samples: 141442)
INFO:root:Loss: 0.4362 +/- 0.0068
INFO:root:Epoch no. 57 of 500 (samples: 141442)
INFO:root:Loss: 0.4347 +/- 0.0084
INFO:root:Epoch no. 58 of 500 (samples: 141442)
INFO:root:Loss: 0.4345 +/- 0.0065
INFO:root:Epoch no. 59 of 500 (samples: 141442)
INFO:root:Loss: 0.4336 +/- 0.007
INFO:root:Epoch no. 60 of 500 (samples: 141442)
INFO:root:Loss: 0.4322 +/- 0.0063
INFO:root:Epoch no. 61 of 500 (samples: 141442)
INFO:root:Loss: 0.4318 +/- 0.0066
INFO:root:Epoch no. 62 of 500 (samples: 141442)
INFO:root:Loss: 0.431 +/- 0.0069
INFO:root:Epoch no. 63 of 500 (samples: 141442)
INFO:root:Loss: 0.4308 +/- 0.0066
INFO:root:Epoch no. 64 of 500 (samples: 141442)
INFO:root:Loss: 0.4297 +/- 0.0059
INFO:root:Epoch no. 65 of 500 (samples: 141442)
INFO:root:Loss: 0.4296 +/- 0.0063
INFO:root:Epoch no. 66 of 500 (samples: 141442)
INFO:root:Loss: 0.4278 +/- 0.0062
INFO:root:Epoch no. 67 of 500 (samples: 141442)
INFO:root:Loss: 0.4283 +/- 0.0053
INFO:root:Epoch no. 68 of 500 (samples: 141442)
INFO:root:Loss: 0.4273 +/- 0.0067
INFO:root:Epoch no. 69 of 500 (samples: 141442)
INFO:root:Loss: 0.427 +/- 0.0071
INFO:root:Epoch no. 70 of 500 (samples: 141442)
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./bin/hyper-cli.py", line 324, in <module>
    main(sys.argv[1:])
  File "./bin/hyper-cli.py", line 293, in main
    visualize=is_visualize)
  File "/home/insight/.local/lib/python3.4/site-packages/hyper-0.0.1-py3.4.egg/hyper/learning/core.py", line 185, in pairwise_training
  File "/home/insight/.local/lib/python3.4/site-packages/Keras-1.0.3-py3.4.egg/keras/models.py", line 409, in fit
    sample_weight=sample_weight)
  File "/home/insight/.local/lib/python3.4/site-packages/Keras-1.0.3-py3.4.egg/keras/engine/training.py", line 1052, in fit
    callback_metrics=callback_metrics)
  File "/home/insight/.local/lib/python3.4/site-packages/Keras-1.0.3-py3.4.egg/keras/engine/training.py", line 790, in _fit_loop
    outs = f(ins_batch)
  File "/home/insight/.local/lib/python3.4/site-packages/Keras-1.0.3-py3.4.egg/keras/backend/theano_backend.py", line 518, in __call__
    return self.function(*inputs)
  File "/usr/local/lib/python3.4/dist-packages/theano/compile/function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/usr/local/lib/python3.4/dist-packages/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/local/lib/python3.4/dist-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
MemoryError: 
Apply node that caused the error: AdvancedSubtensor1(embedding_1_W, Reshape{1}.0)
Toposort index: 19
Inputs types: [TensorType(float32, matrix), TensorType(int32, vector)]
Inputs shapes: [(19, 10000), (42411,)]
Inputs strides: [(40000, 4), (4,)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[Reshape{3}(AdvancedSubtensor1.0, MakeVector{dtype='int64'}.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "/home/insight/.local/lib/python3.4/site-packages/hyper-0.0.1-py3.4.egg/hyper/learning/core.py", line 56, in pairwise_training
    predicate_encoder.add(predicate_embedding_layer)
  File "/home/insight/.local/lib/python3.4/site-packages/Keras-1.0.3-py3.4.egg/keras/models.py", line 114, in add
    layer.create_input_layer(batch_input_shape, input_dtype)
  File "/home/insight/.local/lib/python3.4/site-packages/Keras-1.0.3-py3.4.egg/keras/engine/topology.py", line 341, in create_input_layer
    self(x)
  File "/home/insight/.local/lib/python3.4/site-packages/Keras-1.0.3-py3.4.egg/keras/engine/topology.py", line 485, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/home/insight/.local/lib/python3.4/site-packages/Keras-1.0.3-py3.4.egg/keras/engine/topology.py", line 543, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/home/insight/.local/lib/python3.4/site-packages/Keras-1.0.3-py3.4.egg/keras/engine/topology.py", line 148, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/home/insight/.local/lib/python3.4/site-packages/Keras-1.0.3-py3.4.egg/keras/layers/embeddings.py", line 135, in call
    out = K.gather(W, x)
  File "/home/insight/.local/lib/python3.4/site-packages/Keras-1.0.3-py3.4.egg/keras/backend/theano_backend.py", line 166, in gather
    return reference[indices]

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
